### PR TITLE
DHCP: add ServerId in REQUEST message

### LINKED ISSUE #249: DHCP: REQUEST should send the `ServerId` (option 54) for dnsmasq
### Describe the Problem

Trying to get DHCP working with my local network where the PC is running dnsmasq, I saw DISCOVER, OFFER, and REQUEST on the wire but dnsmasq wouldn't react to the latter.

After debugging a while and comparing the DHCP packets to those from other devices, the reason seems to be that this library doesn't send the `ServerId` option (54) in the DHCPREQUEST message. I hacked that in and got a DHCPACK.  (Will make a PR soon.)

#### Expected Behaviour

Device gets an IP assigned.

### Steps to Reproduce

Run the `ambientsensor` or similar example on a network with dnsmasq (here version 2.89)

### Logging

Can be provided if needed.

### PR DESCRIPTION
**Pull request by birkenfeld**
fixes #249

### CODE REVIEW

**Review by newAM — CHANGES_REQUESTED** [review]
Thanks for the bug report & subsequent fix!

Can you add an entry to the changelog?  Feel free to use this, or reword it.

```md
### Fixed
- Fixed compatibility with dnsmasq by adding a server identifier (option 54) to the REQUEST.
```

**Comment by birkenfeld** [comment]
Done, thanks for the review!

**Comment by newAM** [comment]
Let me know if you want me to make a release with this fix!

**Comment by birkenfeld** [comment]
Thanks! I have one more issue, but I need to collect some information to report it properly.

**Pull request merged**
